// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzRh_5_IhtpduiRh9hKiHKMyI7QzVML1g',
    appId: '1:849028550491:web:8bfbd1d13bb62f6f13d47e',
    messagingSenderId: '849028550491',
    projectId: 'chama-96d8d',
    authDomain: 'chama-96d8d.firebaseapp.com',
    storageBucket: 'chama-96d8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40sd9DaZYBB6B-BRCx7v0ojOvB24HdhY',
    appId: '1:849028550491:android:8eca822f40e847a413d47e',
    messagingSenderId: '849028550491',
    projectId: 'chama-96d8d',
    storageBucket: 'chama-96d8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxo8LzZ-4mBd5_uyjsUC5PXLO5chEdkZI',
    appId: '1:849028550491:ios:057c5ca298b0327113d47e',
    messagingSenderId: '849028550491',
    projectId: 'chama-96d8d',
    storageBucket: 'chama-96d8d.firebasestorage.app',
    iosBundleId: 'com.example.kadhiSaccoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxo8LzZ-4mBd5_uyjsUC5PXLO5chEdkZI',
    appId: '1:849028550491:ios:057c5ca298b0327113d47e',
    messagingSenderId: '849028550491',
    projectId: 'chama-96d8d',
    storageBucket: 'chama-96d8d.firebasestorage.app',
    iosBundleId: 'com.example.kadhiSaccoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzRh_5_IhtpduiRh9hKiHKMyI7QzVML1g',
    appId: '1:849028550491:web:7e5d3fa8cfddee3413d47e',
    messagingSenderId: '849028550491',
    projectId: 'chama-96d8d',
    authDomain: 'chama-96d8d.firebaseapp.com',
    storageBucket: 'chama-96d8d.firebasestorage.app',
  );
}
